modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="eidolon" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Eidolon" #mandatory
authors="elucent" #optional
description='''
A spooky magic mod about necromancy.
'''
[[dependencies.eidolon]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2, 1.19.3)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.eidolon]]
modId = "curios"
mandatory = true
versionRange = "[1.19-5.0.7.1,)"
ordering = "AFTER"
side = "BOTH"
